language: java
jdk: oraclejdk7
before_install:
  # Install base Android SDK
  - sudo apt-get update -qq
  - if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch > /dev/null; fi
  - wget http://dl.google.com/android/android-sdk_r22.0.5-linux.tgz
  - tar -zxf android-sdk_r22.0.5-linux.tgz
  - export ANDROID_HOME=$PWD/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools

  # install android build tools
  - wget https://dl-ssl.google.com/android/repository/build-tools_r18.0.1-linux.zip
  - unzip build-tools_r18.0.1-linux.zip -d $ANDROID_HOME
  - mkdir -p $ANDROID_HOME/build-tools/
  - mv $ANDROID_HOME/android-4.3 $ANDROID_HOME/build-tools/18.0.1


  # Install required Android components.
  - echo y | android update sdk --filter platform-tools --no-ui --force > /dev/null
  - echo y | android update sdk --filter tools --no-ui --force > /dev/null
  - echo y | android update sdk --filter build-tools-17.0.0 --no-ui --force > /dev/null

  - echo y | android update sdk --filter android-16 --no-ui --force > /dev/null
  - echo y | android update sdk --filter android-17 --no-ui --force > /dev/null
  - echo y | android update sdk --filter android-18 --no-ui --force > /dev/null
  - echo y | android update sdk --filter extra-android-support --no-ui --force > /dev/null
  - echo y | android update sdk --filter extra-android-m2repository --no-ui --force > /dev/null

notifications:
  hipchat: 677a00c745ac4ea1f5e1c8cf470a97@Mothership
install: ./gradlew assemble --stacktrace
script: ./gradlew check --stacktrace --info